//make a new array with this, adding up all the "Cost" fields, while grouping each vendor number together and then grouping each GL number together (one GL number per object in the array)
//the new array will just be an array of objects, but with the data summed and only 1 object per vendor number, unless multiple GL numbers, then it would have another object with same vendor number and diff GL
//import this into NS to make a JE(Journal Entry)
const purchArray = [
    {
      "InvoiceDate": "2021-04-12",
      "InvoiceTotal": "13.2700",
      "InvoiceMOP": "Cash",
      "InvoiceType": "S",
      "InvoiceDetail": {
        "InvoiceDetail": [
          {
            "InvoiceNumber": "1142",
            "VendorNumber": "7337",
            "VendorName": "HOMETOWN FOODS",
            "LineType": "product",
            "Quantity": "3",
            "UnitsInCase": "1",
            "CatNO": "2901",
            "CategoryDescription": "Prepared Foods",
            "Cost": "5.34",
            "Retail": "0",
            "GLnumber": "5007",
            "ItemName": "ICEBERG LETTUCE",
            "ProductID": "110000008129",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "1142",
            "VendorNumber": "7337",
            "VendorName": "HOMETOWN FOODS",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "3.5",
            "CatNO": "2901",
            "CategoryDescription": "Prepared Foods",
            "Cost": "4.83",
            "Retail": "0",
            "GLnumber": "5007",
            "ItemName": "REGULAR TOMATO",
            "ProductID": "110000006858",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "1142",
            "VendorNumber": "7338",
            "VendorName": "HOMETOWN FOODS",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "1",
            "CatNO": "2901",
            "CategoryDescription": "Prepared Foods",
            "Cost": "2.09",
            "Retail": "0",
            "GLnumber": "5007",
            "ItemName": "BST-CH PNK&WFL SYRUP",
            "ProductID": "110000009039",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "1142",
            "VendorNumber": "7338",
            "VendorName": "HOMETOWN FOODS",
            "LineType": "tax",
            "Quantity": "0",
            "UnitsInCase": "0",
            "CatNO": "0",
            "CategoryDescription": {},
            "Cost": "1.01",
            "Retail": "0",
            "GLnumber": {},
            "ItemName": {},
            "ProductID": {},
            "TaxService": {}
          }
        ]
      }
    },
    {
      "InvoiceDate": "2021-04-12",
      "InvoiceTotal": "1575.4000",
      "InvoiceMOP": "Credit",
      "InvoiceType": "S",
      "InvoiceDetail": {
        "InvoiceDetail": [
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "2",
            "UnitsInCase": "2",
            "CatNO": "601",
            "CategoryDescription": "Pop/Soda",
            "Cost": "20.84",
            "Retail": "52.32",
            "GLnumber": "1007.9",
            "ItemName": "Coke 12pk",
            "ProductID": "14900002890",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "2",
            "CatNO": "601",
            "CategoryDescription": "Pop/Soda",
            "Cost": "10.42",
            "Retail": "26.16",
            "GLnumber": "1007.9",
            "ItemName": "Sprite 12pk",
            "ProductID": "14900002892",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "2",
            "UnitsInCase": "2",
            "CatNO": "601",
            "CategoryDescription": "Pop/Soda",
            "Cost": "20.84",
            "Retail": "47.52",
            "GLnumber": "1007.9",
            "ItemName": "Dr Pepper 12pk",
            "ProductID": "17800008216",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "2",
            "CatNO": "601",
            "CategoryDescription": "Pop/Soda",
            "Cost": "10.42",
            "Retail": "23.76",
            "GLnumber": "1007.9",
            "ItemName": "Diet Dr Pepper 12pk",
            "ProductID": "17800008316",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "24",
            "CatNO": "601",
            "CategoryDescription": "Pop/Soda",
            "Cost": "20.5",
            "Retail": "35.76",
            "GLnumber": "1007.9",
            "ItemName": "Dr Pepper 16oz",
            "ProductID": "17800000586",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "12",
            "CatNO": "601",
            "CategoryDescription": "Pop/Soda",
            "Cost": "17.68",
            "Retail": "27.48",
            "GLnumber": "1007.9",
            "ItemName": "Sprite 1ltr",
            "ProductID": "14900002319",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "12",
            "CatNO": "601",
            "CategoryDescription": "Pop/Soda",
            "Cost": "17.68",
            "Retail": "27.48",
            "GLnumber": "1007.9",
            "ItemName": "Coke 1Ltr",
            "ProductID": "14900000522",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "2",
            "UnitsInCase": "12",
            "CatNO": "601",
            "CategoryDescription": "Pop/Soda",
            "Cost": "35.36",
            "Retail": "52.56",
            "GLnumber": "1007.9",
            "ItemName": "Dr Pepper 1ltr",
            "ProductID": "17800008245",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "24",
            "CatNO": "601",
            "CategoryDescription": "Pop/Soda",
            "Cost": "28.83",
            "Retail": "50.16",
            "GLnumber": "1007.9",
            "ItemName": "Coke Cherry 20oz",
            "ProductID": "14900001801",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "24",
            "CatNO": "601",
            "CategoryDescription": "Pop/Soda",
            "Cost": "23.65",
            "Retail": "47.76",
            "GLnumber": "1007.9",
            "ItemName": "Barqs  RootBeer 20oz",
            "ProductID": "14900002392",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "24",
            "CatNO": "601",
            "CategoryDescription": "Pop/Soda",
            "Cost": "28.83",
            "Retail": "50.16",
            "GLnumber": "1007.9",
            "ItemName": "Sprite 20oz",
            "ProductID": "14900000764",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "24",
            "CatNO": "601",
            "CategoryDescription": "Pop/Soda",
            "Cost": "28.83",
            "Retail": "50.16",
            "GLnumber": "1007.9",
            "ItemName": "Coke Vanilla 20oz",
            "ProductID": "14900003117",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "4",
            "UnitsInCase": "24",
            "CatNO": "601",
            "CategoryDescription": "Pop/Soda",
            "Cost": "115.32",
            "Retail": "200.64",
            "GLnumber": "1007.9",
            "ItemName": "Dr Pepper 20oz",
            "ProductID": "17800008240",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "2",
            "UnitsInCase": "24",
            "CatNO": "601",
            "CategoryDescription": "Pop/Soda",
            "Cost": "57.66",
            "Retail": "100.32",
            "GLnumber": "1007.9",
            "ItemName": "Coke 20oz",
            "ProductID": "14900000044",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "24",
            "CatNO": "601",
            "CategoryDescription": "Pop/Soda",
            "Cost": "28.83",
            "Retail": "50.16",
            "GLnumber": "1007.9",
            "ItemName": "Diet Coke 20oz",
            "ProductID": "14900000045",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "24",
            "CatNO": "601",
            "CategoryDescription": "Pop/Soda",
            "Cost": "28.83",
            "Retail": "50.16",
            "GLnumber": "1007.9",
            "ItemName": "CHERRY COKE ZERO 20O",
            "ProductID": "14900004754",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "24",
            "CatNO": "601",
            "CategoryDescription": "Pop/Soda",
            "Cost": "28.83",
            "Retail": "50.16",
            "GLnumber": "1007.9",
            "ItemName": "SPRITE LEMONADE 20OZ",
            "ProductID": "14900007872",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "24",
            "CatNO": "601",
            "CategoryDescription": "Pop/Soda",
            "Cost": "28.83",
            "Retail": "50.16",
            "GLnumber": "1007.9",
            "ItemName": "Sprite Ginger 20oz",
            "ProductID": "14900009320",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "24",
            "CatNO": "601",
            "CategoryDescription": "Pop/Soda",
            "Cost": "28.83",
            "Retail": "50.16",
            "GLnumber": "1007.9",
            "ItemName": "Dr. Pepper & Cream S",
            "ProductID": "17800003544",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "24",
            "CatNO": "601",
            "CategoryDescription": "Pop/Soda",
            "Cost": "28.83",
            "Retail": "50.16",
            "GLnumber": "1007.9",
            "ItemName": "DR  PEPPER Z SRCY",
            "ProductID": "17800003540",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "8",
            "CatNO": "601",
            "CategoryDescription": "Pop/Soda",
            "Cost": "14.64",
            "Retail": "19.12",
            "GLnumber": "1007.9",
            "ItemName": "Coke 2ltr",
            "ProductID": "14900005010",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "8",
            "CatNO": "601",
            "CategoryDescription": "Pop/Soda",
            "Cost": "14.64",
            "Retail": "19.12",
            "GLnumber": "1007.9",
            "ItemName": "DIET COKE 2LTR",
            "ProductID": "14900005011",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "8",
            "CatNO": "601",
            "CategoryDescription": "Pop/Soda",
            "Cost": "14.64",
            "Retail": "19.12",
            "GLnumber": "1007.9",
            "ItemName": "Sprite 2ltr",
            "ProductID": "14900005015",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "12",
            "CatNO": "701",
            "CategoryDescription": "Packaged Beverages (Non-alcoholic)",
            "Cost": "14.84",
            "Retail": "23.88",
            "GLnumber": "1007.9",
            "ItemName": "Vita-Water Power C D",
            "ProductID": "178616201000",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "12",
            "CatNO": "701",
            "CategoryDescription": "Packaged Beverages (Non-alcoholic)",
            "Cost": "9.33",
            "Retail": "16.68",
            "GLnumber": "1007.9",
            "ItemName": "TYEDGORGBRS 10.10OZ",
            "ProductID": "188331509029",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "24",
            "CatNO": "701",
            "CategoryDescription": "Packaged Beverages (Non-alcoholic)",
            "Cost": "31.9",
            "Retail": "50.16",
            "GLnumber": "1007.9",
            "ItemName": "Minute Maid Cran Gra",
            "ProductID": "12500005200",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "12",
            "CatNO": "701",
            "CategoryDescription": "Packaged Beverages (Non-alcoholic)",
            "Cost": "14",
            "Retail": "23.88",
            "GLnumber": "1007.9",
            "ItemName": "BOARMR SPOSBRB 16OZ",
            "ProductID": "185817600206",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "12",
            "CatNO": "701",
            "CategoryDescription": "Packaged Beverages (Non-alcoholic)",
            "Cost": "14",
            "Retail": "23.88",
            "GLnumber": "1007.9",
            "ItemName": "BA SPD FRPN 16OZ",
            "ProductID": "185817600213",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "12",
            "CatNO": "701",
            "CategoryDescription": "Packaged Beverages (Non-alcoholic)",
            "Cost": "14",
            "Retail": "23.88",
            "GLnumber": "1007.9",
            "ItemName": "BodyArmor Blackberry",
            "ProductID": "185817600211",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "12",
            "CatNO": "701",
            "CategoryDescription": "Packaged Beverages (Non-alcoholic)",
            "Cost": "14",
            "Retail": "23.88",
            "GLnumber": "1007.9",
            "ItemName": "BOARMR SPD WMNSBRY 1",
            "ProductID": "185817600242",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "12",
            "CatNO": "701",
            "CategoryDescription": "Packaged Beverages (Non-alcoholic)",
            "Cost": "14",
            "Retail": "23.88",
            "GLnumber": "1007.9",
            "ItemName": "BodyArmor Pineapple/",
            "ProductID": "185817600252",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "12",
            "CatNO": "701",
            "CategoryDescription": "Packaged Beverages (Non-alcoholic)",
            "Cost": "15",
            "Retail": "27.48",
            "GLnumber": "1007.9",
            "ItemName": "BA SPRWTR 1L",
            "ProductID": "185817600215",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "24",
            "CatNO": "701",
            "CategoryDescription": "Packaged Beverages (Non-alcoholic)",
            "Cost": "18.8",
            "Retail": "30.96",
            "GLnumber": "1007.9",
            "ItemName": "POWERADE GRAPE 20OZ",
            "ProductID": "14900004526",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "15",
            "CatNO": "701",
            "CategoryDescription": "Packaged Beverages (Non-alcoholic)",
            "Cost": "16.9",
            "Retail": "29.85",
            "GLnumber": "1007.9",
            "ItemName": "PA Mntn Blast 28oz",
            "ProductID": "14900007935",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "2",
            "UnitsInCase": "12",
            "CatNO": "701",
            "CategoryDescription": "Packaged Beverages (Non-alcoholic)",
            "Cost": "28.08",
            "Retail": "47.76",
            "GLnumber": "1007.9",
            "ItemName": "GOLD PEAK SWEETENED",
            "ProductID": "18390000575",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "12",
            "CatNO": "701",
            "CategoryDescription": "Packaged Beverages (Non-alcoholic)",
            "Cost": "14.04",
            "Retail": "23.88",
            "GLnumber": "1007.9",
            "ItemName": "GOLDPEAK GREEN 18.5O",
            "ProductID": "18390000597",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "12",
            "CatNO": "701",
            "CategoryDescription": "Packaged Beverages (Non-alcoholic)",
            "Cost": "14.04",
            "Retail": "23.88",
            "GLnumber": "1007.9",
            "ItemName": "GOLD PEAK SL SWEET 1",
            "ProductID": "14900007249",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "12",
            "CatNO": "701",
            "CategoryDescription": "Packaged Beverages (Non-alcoholic)",
            "Cost": "10.6",
            "Retail": "17.88",
            "GLnumber": "1007.9",
            "ItemName": "Peace Tea Georgia Pe",
            "ProductID": "14900007043",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "2",
            "UnitsInCase": "12",
            "CatNO": "701",
            "CategoryDescription": "Packaged Beverages (Non-alcoholic)",
            "Cost": "24.96",
            "Retail": "47.76",
            "GLnumber": "1007.9",
            "ItemName": "Dasani 1ltr",
            "ProductID": "14900002656",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "24",
            "CatNO": "701",
            "CategoryDescription": "Packaged Beverages (Non-alcoholic)",
            "Cost": "24.7",
            "Retail": "40.56",
            "GLnumber": "1007.9",
            "ItemName": "Topo Chico LL 20oz",
            "ProductID": "12113611018",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "24",
            "CatNO": "701",
            "CategoryDescription": "Packaged Beverages (Non-alcoholic)",
            "Cost": "18.48",
            "Retail": "30.96",
            "GLnumber": "1007.9",
            "ItemName": "Dasani 20oz",
            "ProductID": "14900000977",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "24",
            "CatNO": "701",
            "CategoryDescription": "Packaged Beverages (Non-alcoholic)",
            "Cost": "30.24",
            "Retail": "50.16",
            "GLnumber": "1007.9",
            "ItemName": "Smartwater 700ml",
            "ProductID": "178616200151",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "24",
            "CatNO": "703",
            "CategoryDescription": "Energy Drink",
            "Cost": "33.66",
            "Retail": "69.36",
            "GLnumber": "1007.9",
            "ItemName": "Monster Green 16oz",
            "ProductID": "17084781116",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "24",
            "CatNO": "703",
            "CategoryDescription": "Energy Drink",
            "Cost": "33.66",
            "Retail": "69.36",
            "GLnumber": "1007.9",
            "ItemName": "Monster Blue 16oz",
            "ProductID": "17084781126",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "24",
            "CatNO": "703",
            "CategoryDescription": "Energy Drink",
            "Cost": "33.66",
            "Retail": "69.36",
            "GLnumber": "1007.9",
            "ItemName": "Monster Assault 16oz",
            "ProductID": "17084781170",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "24",
            "CatNO": "703",
            "CategoryDescription": "Energy Drink",
            "Cost": "33.66",
            "Retail": "69.36",
            "GLnumber": "1007.9",
            "ItemName": "Monster Zero Ultra",
            "ProductID": "17084701247",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "12",
            "CatNO": "703",
            "CategoryDescription": "Energy Drink",
            "Cost": "27.12",
            "Retail": "44.28",
            "GLnumber": "1007.9",
            "ItemName": "Monster Green 24oz",
            "ProductID": "17084781124",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "12",
            "CatNO": "703",
            "CategoryDescription": "Energy Drink",
            "Cost": "27.12",
            "Retail": "44.28",
            "GLnumber": "1007.9",
            "ItemName": "Monster UltraZero 24",
            "ProductID": "17084701770",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "12",
            "CatNO": "703",
            "CategoryDescription": "Energy Drink",
            "Cost": "27.12",
            "Retail": "44.28",
            "GLnumber": "1007.9",
            "ItemName": "Nos Energy 22oz",
            "ProductID": "181515402007",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "12",
            "CatNO": "901",
            "CategoryDescription": "Milk Products",
            "Cost": "13.13",
            "Retail": "23.88",
            "GLnumber": "1007.9",
            "ItemName": "Yup Chocolate 14oz",
            "ProductID": "181162002039",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "3",
            "UnitsInCase": "1",
            "CatNO": "3101",
            "CategoryDescription": "Fountain",
            "Cost": "262.95",
            "Retail": "0",
            "GLnumber": "5007",
            "ItemName": "Dr Pepper BIB",
            "ProductID": "15490071054",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "14754203347",
            "VendorNumber": "1295",
            "VendorName": "COCA-COLA",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "1",
            "CatNO": "3101",
            "CategoryDescription": "Fountain",
            "Cost": "87.65",
            "Retail": "0",
            "GLnumber": "5007",
            "ItemName": "DIET COKE 5 GAL BAG",
            "ProductID": "14900098091",
            "TaxService": {}
          }
        ]
      }
    },
    {
      "InvoiceDate": "2021-04-12",
      "InvoiceTotal": "314.4400",
      "InvoiceMOP": "Credit",
      "InvoiceType": "S",
      "InvoiceDetail": {
        "InvoiceDetail": [
          {
            "InvoiceNumber": "392473",
            "VendorNumber": "6399",
            "VendorName": "GRIMSLEY'S JANITORIAL SUPPLIES",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "1",
            "CatNO": "3101",
            "CategoryDescription": "Fountain",
            "Cost": "59",
            "Retail": "0",
            "GLnumber": "5007",
            "ItemName": "EARNHEART CUP DRINK",
            "ProductID": "110000002669",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "392473",
            "VendorNumber": "6399",
            "VendorName": "GRIMSLEY'S JANITORIAL SUPPLIES",
            "LineType": "product",
            "Quantity": "2",
            "UnitsInCase": "5",
            "CatNO": "3101",
            "CategoryDescription": "Fountain",
            "Cost": "47.54",
            "Retail": "0",
            "GLnumber": "5007",
            "ItemName": "LID STRAW-SLOT TRANS",
            "ProductID": "110000006855",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "392473",
            "VendorNumber": "6399",
            "VendorName": "GRIMSLEY'S JANITORIAL SUPPLIES",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "1",
            "CatNO": "3001",
            "CategoryDescription": "Coffee",
            "Cost": "44.88",
            "Retail": "0",
            "GLnumber": "5007",
            "ItemName": "LID, CAPPUCINO, WHI",
            "ProductID": "110000007504",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "392473",
            "VendorNumber": "6399",
            "VendorName": "GRIMSLEY'S JANITORIAL SUPPLIES",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "1",
            "CatNO": "9901",
            "CategoryDescription": "Store Use/Supply",
            "Cost": "68.04",
            "Retail": "0",
            "GLnumber": "6003.4.11",
            "ItemName": "NAPKIN, XPRESSNAP, W",
            "ProductID": "110000000049",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "392473",
            "VendorNumber": "6399",
            "VendorName": "GRIMSLEY'S JANITORIAL SUPPLIES",
            "LineType": "product",
            "Quantity": "2",
            "UnitsInCase": "50",
            "CatNO": "2902",
            "CategoryDescription": "Pizza",
            "Cost": "66.86",
            "Retail": "0",
            "GLnumber": "5007",
            "ItemName": "PIZZA BOX TAN/WHT 14",
            "ProductID": "110000006949",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "392473",
            "VendorNumber": "6399",
            "VendorName": "GRIMSLEY'S JANITORIAL SUPPLIES",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "1",
            "CatNO": "9901",
            "CategoryDescription": "Store Use/Supply",
            "Cost": "28.12",
            "Retail": "0",
            "GLnumber": "6003.4.11",
            "ItemName": "CARRYOUT FOAM 9X9 1C",
            "ProductID": "110000004782",
            "TaxService": {}
          }
        ]
      }
    },
    {
      "InvoiceDate": "2021-04-12",
      "InvoiceTotal": "20.1600",
      "InvoiceMOP": "Credit",
      "InvoiceType": "S",
      "InvoiceDetail": {
        "InvoiceDetail": [
          {
            "InvoiceNumber": "392474",
            "VendorNumber": "6399",
            "VendorName": "GRIMSLEY'S JANITORIAL SUPPLIES",
            "LineType": "product",
            "Quantity": "2",
            "UnitsInCase": "1",
            "CatNO": "9901",
            "CategoryDescription": "Store Use/Supply",
            "Cost": "7.74",
            "Retail": "0",
            "GLnumber": "6003.4.11",
            "ItemName": "CLNR, GP, XCELENTE,",
            "ProductID": "110000003239",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "392474",
            "VendorNumber": "6399",
            "VendorName": "GRIMSLEY'S JANITORIAL SUPPLIES",
            "LineType": "product",
            "Quantity": "1",
            "UnitsInCase": "1",
            "CatNO": "9901",
            "CategoryDescription": "Store Use/Supply",
            "Cost": "10.88",
            "Retail": "0",
            "GLnumber": "6003.4.11",
            "ItemName": "CLNR, GP, XCELENTE G",
            "ProductID": "110000002657",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "392474",
            "VendorNumber": "6399",
            "VendorName": "GRIMSLEY'S JANITORIAL SUPPLIES",
            "LineType": "tax",
            "Quantity": "0",
            "UnitsInCase": "0",
            "CatNO": "0",
            "CategoryDescription": {},
            "Cost": "1.54",
            "Retail": "0",
            "GLnumber": {},
            "ItemName": {},
            "ProductID": {},
            "TaxService": {}
          }
        ]
      }
    },
    {
      "InvoiceDate": "2021-04-12",
      "InvoiceTotal": "19306.9300",
      "InvoiceMOP": "EFT",
      "InvoiceType": "F",
      "InvoiceDetail": {
        "InvoiceDetail": [
          {
            "InvoiceNumber": "2124112062",
            "VendorNumber": "1303",
            "VendorName": "EARNHEART TRANSPORTATION",
            "LineType": "product",
            "Quantity": "1001",
            "UnitsInCase": "1",
            "CatNO": "0",
            "CategoryDescription": {},
            "Cost": "1981.98",
            "Retail": "0",
            "GLnumber": {},
            "ItemName": "Off Road Diesel",
            "ProductID": "28",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "2124112062",
            "VendorNumber": "1303",
            "VendorName": "EARNHEART TRANSPORTATION",
            "LineType": "product",
            "Quantity": "3000",
            "UnitsInCase": "1",
            "CatNO": "0",
            "CategoryDescription": {},
            "Cost": "7230",
            "Retail": "0",
            "GLnumber": {},
            "ItemName": "Diesel",
            "ProductID": "26",
            "TaxService": {}
          },
          {
            "InvoiceNumber": "2124112062",
            "VendorNumber": "1303",
            "VendorName": "EARNHEART TRANSPORTATION",
            "LineType": "product",
            "Quantity": "3998",
            "UnitsInCase": "1",
            "CatNO": "0",
            "CategoryDescription": {},
            "Cost": "10094.95",
            "Retail": "0",
            "GLnumber": {},
            "ItemName": "Regular",
            "ProductID": "21",
            "TaxService": {}
          }
        ]
      }
    },
    {
      "InvoiceDate": "2021-04-12",
      "InvoiceTotal": "0.0000",
      "InvoiceMOP": "Cash",
      "InvoiceType": "NI",
      "InvoiceDetail": {
        "InvoiceDetail": {
          "InvoiceNumber": "0",
          "VendorNumber": {},
          "VendorName": "IMOA Vendor",
          "LineType": "product",
          "Quantity": "1",
          "UnitsInCase": "1",
          "CatNO": "15",
          "CategoryDescription": {},
          "Cost": "0",
          "Retail": "670.75",
          "GLnumber": {},
          "ItemName": {},
          "ProductID": {},
          "TaxService": {}
        }
      }
    },
    {
      "InvoiceDate": "2021-04-12",
      "InvoiceTotal": "0.0000",
      "InvoiceMOP": "Cash",
      "InvoiceType": "NI",
      "InvoiceDetail": {
        "InvoiceDetail": {
          "InvoiceNumber": "0",
          "VendorNumber": {},
          "VendorName": "IMOA Vendor",
          "LineType": "product",
          "Quantity": "1",
          "UnitsInCase": "1",
          "CatNO": "2902",
          "CategoryDescription": "Pizza",
          "Cost": "0",
          "Retail": "190.53",
          "GLnumber": "5007",
          "ItemName": {},
          "ProductID": {},
          "TaxService": {}
        }
      }
    },
    {
      "InvoiceDate": "2021-04-12",
      "InvoiceTotal": "0.0000",
      "InvoiceMOP": "Cash",
      "InvoiceType": "NI",
      "InvoiceDetail": {
        "InvoiceDetail": {
          "InvoiceNumber": "0",
          "VendorNumber": {},
          "VendorName": "IMOA Vendor",
          "LineType": "product",
          "Quantity": "1",
          "UnitsInCase": "1",
          "CatNO": "15",
          "CategoryDescription": {},
          "Cost": "0",
          "Retail": "41.35",
          "GLnumber": {},
          "ItemName": {},
          "ProductID": {},
          "TaxService": {}
        }
      }
    },
    {
      "InvoiceDate": "2021-04-12",
      "InvoiceTotal": "0.0000",
      "InvoiceMOP": "Cash",
      "InvoiceType": "NI",
      "InvoiceDetail": {
        "InvoiceDetail": {
          "InvoiceNumber": "0",
          "VendorNumber": {},
          "VendorName": "IMOA Vendor",
          "LineType": "product",
          "Quantity": "1",
          "UnitsInCase": "1",
          "CatNO": "15",
          "CategoryDescription": {},
          "Cost": "0",
          "Retail": "222.69",
          "GLnumber": {},
          "ItemName": {},
          "ProductID": {},
          "TaxService": {}
        }
      }
    },
    {
      "InvoiceDate": "2021-04-12",
      "InvoiceTotal": "0.0000",
      "InvoiceMOP": "Cash",
      "InvoiceType": "NI",
      "InvoiceDetail": {
        "InvoiceDetail": {
          "InvoiceNumber": "0",
          "VendorNumber": {},
          "VendorName": "IMOA Vendor",
          "LineType": "product",
          "Quantity": "1",
          "UnitsInCase": "1",
          "CatNO": "201",
          "CategoryDescription": "Cigarettes",
          "Cost": "0",
          "Retail": "18.4",
          "GLnumber": "1007.9",
          "ItemName": {},
          "ProductID": {},
          "TaxService": {}
        }
      }
    }
  ]

let parsedArray = [];

//Loop Through the Records in the purch Array
for(let i = 0; i < purchArray.length; i++){
  let currentRecord = purchArray[i];

  //Loop Through the Current Records Invoice Deatils
  for(let j = 0; j < currentRecord.InvoiceDetail.InvoiceDetail.length; j++){
    let currentInvoice = currentRecord.InvoiceDetail.InvoiceDetail[j];

    let vendorAlreadyExisted = false;
    let glAlreadyExisted = false;
    for(let k = 0; k < parsedArray.length; k++){
      if(parsedArray[k].VendorNumber == currentInvoice.VendorNumber){
        vendorAlreadyExisted = true;
        
        if(parsedArray[k].GLnumber == currentInvoice.GLnumber){
          glAlreadyExisted = true;
        }

        
      }
    }

    if(!vendorAlreadyExisted && !glAlreadyExisted){
      parsedArray.push(currentInvoice);
    }
  }
}


for(let i = 0; i < parsedArray.length; i++){
  console.log(parsedArray[i]);
}

function checkIfVendorExisit(vendorId){
  for(let i = 0; i < parsedArray.length; i++){
    if(parsedArray[i].VendorNumber == vendorId){
      console.log('true');
      return true;
    }
  }

  return false;
}